### PR TITLE
Fix some more typos

### PR DESCRIPTION
**Pull request by jdreesen**

### CODE REVIEW

**Comment by Spomky** [comment]
Hi @jdreesen,

Thank you so much for the doc review.
It looks like you are reading every single pages.
That's very kind of you.

Just let me know when you think it is ready to be merged.

**Comment by jdreesen** [comment]
That's it for today. I'll read the deep-dive section in the next days or so, not sure when I have the time. 

You can merge this if you want, I'll create a new PR when I read the next chapters and maybe spot some more typos.

Note that I'm not a native speaker, which is why I mostly corrected typos and not grammatical errors. It's just what I spotted by reading through the docs :)

**Comment by jdreesen** [comment]
Thank you for this project, it looks really awesome and is much-needed for the future of web authentication! :)

**Comment by jdreesen** [comment]
Wait, I have some more typos ;)

**Comment by jdreesen** [comment]
Now I'm done for today, ready to merge!

**Comment by Spomky** [comment]
Many thanks! Merged.

**Pull request merged**
